# Generated by Django 5.2.14 on 2026-07-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ontologizar_app", "0002_subject_source_url_subjectmaterial_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conceptrelation",
            name="relation_type",
            field=models.CharField(
                choices=[
                    ("related", "Relacionado"),
                    ("broader", "Más amplio"),
                    ("narrower", "Más estrecho"),
                    ("part_of", "Parte de"),
                    ("has_part", "Tiene como parte a"),
                    ("produces", "Produce"),
                    ("enables", "Permite"),
                    ("participates_in", "Participa en"),
                    ("works_via", "Funciona mediante"),
                    ("evolves_from", "Evoluciona de"),
                    ("evolves_to", "Evoluciona hacia"),
                    ("historically_after", "Viene después de"),
                    ("historically_before", "Viene antes de"),
                    ("appears_in", "Aparece en"),
                    ("invented_by", "Inventado por"),
                    ("used_in", "Se usa en"),
                    ("transmits_to", "Transmite a"),
                    ("may_fail_as", "Puede fallar como"),
                    ("requires_maintenance", "Requiere mantenimiento"),
                    ("may_lead_to", "Puede llevar a"),
                    ("monta_a", "Monta a"),
                    ("escudero_de", "Escudero de"),
                    ("ama_a", "Ama a"),
                    ("ocurre_en", "Ocurre en"),
                    ("advierte_a", "Advierte a"),
                    ("ataca_a", "Ataca a"),
                ],
                default="related",
                max_length=32,
            ),
        ),
    ]
