# Generated by Django 4.2.4 on 2026-06-22 11:12

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProyectoInvestigacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("acron", models.CharField(blank=True, db_index=True, max_length=32)),
                ("titulo", models.CharField(max_length=300)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activa", "Activa"),
                            ("pausada", "Pausada"),
                            ("completada", "Completada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="activa",
                        max_length=20,
                    ),
                ),
                ("fecha_inicio", models.DateField(blank=True, null=True)),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("publico", models.BooleanField(default=True)),
                (
                    "fecha_creacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Proyecto de investigación",
                "verbose_name_plural": "Proyectos de investigación",
                "ordering": ["titulo"],
            },
        ),
    ]
