# Generated by Django 4.2.4 on 2026-06-23 09:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("research_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScientificActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("capability_slug", models.CharField(max_length=32)),
                ("title", models.CharField(max_length=300)),
                ("slug", models.SlugField(max_length=80)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planificada"),
                            ("active", "Activa"),
                            ("completed", "Completada"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.AlterModelOptions(
            name="proyectoinvestigacion",
            options={
                "ordering": ["titulo"],
                "verbose_name": "Cuaderno de investigación",
                "verbose_name_plural": "Cuadernos de investigación",
            },
        ),
        migrations.CreateModel(
            name="ScientificResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("result_type", models.CharField(max_length=32)),
                ("title", models.CharField(max_length=300)),
                ("publish_url", models.URLField(blank=True)),
                ("artifact_url", models.URLField(blank=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="research_app.scientificactivity",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="scientificactivity",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="research_app.proyectoinvestigacion",
            ),
        ),
        migrations.CreateModel(
            name="LearningMarker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("concept_uuid", models.UUIDField(db_index=True)),
                ("subject_slug", models.CharField(max_length=80)),
                ("dictionary_slug", models.CharField(max_length=80)),
                ("taxonomy_slug", models.CharField(max_length=80)),
                ("concept_label", models.CharField(max_length=200)),
                ("jsonld_url", models.URLField(blank=True)),
                ("note", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("interesting", "Interesante"),
                            ("selected", "Seleccionado"),
                            ("used", "Usado"),
                            ("cited", "Citado"),
                        ],
                        default="selected",
                        max_length=20,
                    ),
                ),
                ("created_by", models.CharField(blank=True, max_length=150)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="markers",
                        to="research_app.proyectoinvestigacion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="scientificactivity",
            unique_together={("project", "slug")},
        ),
        migrations.CreateModel(
            name="ProjectCurriculumDeclaration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("capability_slug", models.CharField(db_index=True, max_length=32)),
                (
                    "declared_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="declarations",
                        to="research_app.proyectoinvestigacion",
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "capability_slug")},
            },
        ),
    ]
