# Generated by Django 5.2.14 on 2026-06-23 14:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ontologizar_app", "0002_subject_source_url_subjectmaterial_body"),
    ]

    operations = [
        migrations.CreateModel(
            name="AiramSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "granularity",
                    models.CharField(
                        choices=[
                            ("breve", "Breve"),
                            ("normal", "Normal"),
                            ("profundo", "Profundo"),
                            ("temario", "Temario"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("state", models.JSONField(blank=True, default=dict)),
                ("owner_username", models.CharField(blank=True, max_length=150)),
                (
                    "session_key",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("is_bookmarked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bookmarked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ontologizar_app.taxonomynode",
                    ),
                ),
                (
                    "root_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="airam_sessions_root",
                        to="ontologizar_app.taxonomynode",
                    ),
                ),
                (
                    "taxonomy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="airam_sessions",
                        to="ontologizar_app.taxonomy",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
