# Generated by Django 5.2.14 on 2026-07-06 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ontologizar_app", "0003_alter_conceptrelation_relation_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Capitulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parte",
                    models.CharField(
                        choices=[("I", "Primera parte"), ("II", "Segunda parte")],
                        max_length=3,
                    ),
                ),
                ("numero", models.PositiveIntegerField()),
                ("numeral", models.CharField(max_length=20)),
                ("titulo", models.CharField(blank=True, max_length=500)),
                ("orden", models.PositiveIntegerField()),
                (
                    "dictionary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capitulos",
                        to="ontologizar_app.dictionary",
                    ),
                ),
            ],
            options={
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="Parrafo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orden", models.PositiveIntegerField()),
                ("texto", models.TextField()),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("W", "Worldbuilding"),
                            ("P", "Personaje"),
                            ("N", "Narración"),
                            ("D", "Diálogo"),
                            ("S", "Simbolismo"),
                            ("Q", "Pregunta abierta"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "temporalidad",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pasado_narrativo", "Pasado narrativo"),
                            ("pasado_recordado", "Pasado recordado"),
                            ("pasado_anterior", "Pasado anterior"),
                            ("presente_actual", "Presente actual"),
                            ("presente_historico", "Presente histórico"),
                            ("futuro_previsto", "Futuro previsto"),
                            ("futuro_hipotetico", "Futuro hipotético"),
                            ("futuro_mitico", "Futuro mítico"),
                            ("habitual", "Habitual"),
                            ("simultaneidad", "Simultaneidad"),
                            ("posterioridad", "Posterioridad"),
                            ("atemporalidad", "Atemporalidad"),
                            ("incertidumbre", "Incertidumbre"),
                        ],
                        max_length=50,
                    ),
                ),
                ("subtype", models.CharField(blank=True, max_length=50)),
                ("notas", models.TextField(blank=True)),
                (
                    "capitulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parrafos",
                        to="corpus_app.capitulo",
                    ),
                ),
            ],
            options={
                "ordering": ["capitulo", "orden"],
            },
        ),
        migrations.CreateModel(
            name="MencionSugerida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto_superficie", models.CharField(max_length=200)),
                (
                    "normalizado",
                    models.CharField(blank=True, db_index=True, max_length=220),
                ),
                ("tipo_sugerido", models.CharField(blank=True, max_length=50)),
                ("confianza", models.FloatField(blank=True, null=True)),
                (
                    "fuente",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ner", "NER"),
                            ("noun_chunk", "Frase nominal"),
                            ("entidad_oscura", "Entidad oscura"),
                            ("patron", "Patrón léxico"),
                            ("llm", "LLM"),
                        ],
                        max_length=20,
                    ),
                ),
                ("aceptada", models.BooleanField(blank=True, null=True)),
                (
                    "concept_sugerido",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sugerencias",
                        to="ontologizar_app.concept",
                    ),
                ),
                (
                    "parrafo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menciones_sugeridas",
                        to="corpus_app.parrafo",
                    ),
                ),
            ],
            options={
                "ordering": ["-confianza"],
            },
        ),
        migrations.CreateModel(
            name="Mencion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto_superficie", models.CharField(blank=True, max_length=200)),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menciones",
                        to="ontologizar_app.concept",
                    ),
                ),
                (
                    "parrafo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menciones",
                        to="corpus_app.parrafo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LabelSugerida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        choices=[
                            ("W", "Worldbuilding"),
                            ("P", "Personaje"),
                            ("N", "Narración"),
                            ("D", "Diálogo"),
                            ("S", "Simbolismo"),
                            ("Q", "Pregunta abierta"),
                        ],
                        max_length=1,
                    ),
                ),
                ("razon", models.TextField(blank=True)),
                ("confianza", models.FloatField(blank=True, null=True)),
                ("fuente", models.CharField(default="llm", max_length=20)),
                ("aceptada", models.BooleanField(blank=True, null=True)),
                (
                    "parrafo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labels_sugeridas",
                        to="corpus_app.parrafo",
                    ),
                ),
            ],
            options={
                "ordering": ["-confianza"],
            },
        ),
        migrations.CreateModel(
            name="RelacionSugerida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origen_texto", models.CharField(max_length=200)),
                ("relation_type", models.CharField(max_length=80)),
                ("destino_texto", models.CharField(max_length=200)),
                ("evidencia", models.TextField(blank=True)),
                ("confianza", models.FloatField(blank=True, null=True)),
                ("fuente", models.CharField(default="llm", max_length=20)),
                (
                    "relation_type_normalizado",
                    models.CharField(blank=True, max_length=32),
                ),
                ("aceptada", models.BooleanField(blank=True, null=True)),
                (
                    "destino_concept",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ontologizar_app.concept",
                    ),
                ),
                (
                    "origen_concept",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ontologizar_app.concept",
                    ),
                ),
                (
                    "parrafo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relaciones_sugeridas",
                        to="corpus_app.parrafo",
                    ),
                ),
            ],
            options={
                "ordering": ["-confianza"],
            },
        ),
        migrations.CreateModel(
            name="TemporalidadSugerida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fuente", models.CharField(default="airam", max_length=30)),
                (
                    "orientacion",
                    models.CharField(
                        choices=[
                            ("pasado_narrativo", "Pasado narrativo"),
                            ("pasado_recordado", "Pasado recordado"),
                            ("pasado_anterior", "Pasado anterior"),
                            ("presente_actual", "Presente actual"),
                            ("presente_historico", "Presente histórico"),
                            ("futuro_previsto", "Futuro previsto"),
                            ("futuro_hipotetico", "Futuro hipotético"),
                            ("futuro_mitico", "Futuro mítico"),
                            ("habitual", "Habitual"),
                            ("simultaneidad", "Simultaneidad"),
                            ("posterioridad", "Posterioridad"),
                            ("atemporalidad", "Atemporalidad"),
                            ("incertidumbre", "Incertidumbre"),
                        ],
                        max_length=50,
                    ),
                ),
                ("confianza", models.FloatField(blank=True, null=True)),
                ("marcador", models.TextField(blank=True)),
                ("aceptada", models.BooleanField(blank=True, null=True)),
                ("notas", models.TextField(blank=True)),
                (
                    "parrafo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temporalidades_sugeridas",
                        to="corpus_app.parrafo",
                    ),
                ),
            ],
            options={
                "ordering": ["-confianza"],
            },
        ),
        migrations.AddConstraint(
            model_name="capitulo",
            constraint=models.UniqueConstraint(
                fields=("dictionary", "parte", "numero"), name="unique_capitulo"
            ),
        ),
        migrations.AddConstraint(
            model_name="parrafo",
            constraint=models.UniqueConstraint(
                fields=("capitulo", "orden"), name="unique_parrafo_orden"
            ),
        ),
        migrations.AddConstraint(
            model_name="mencionsugerida",
            constraint=models.UniqueConstraint(
                fields=("parrafo", "texto_superficie", "fuente"),
                name="unique_mencion_sugerida",
            ),
        ),
        migrations.AddConstraint(
            model_name="mencion",
            constraint=models.UniqueConstraint(
                fields=("parrafo", "concept"), name="unique_mencion"
            ),
        ),
        migrations.AddConstraint(
            model_name="labelsugerida",
            constraint=models.UniqueConstraint(
                fields=("parrafo", "fuente"), name="unique_label_sugerida"
            ),
        ),
        migrations.AddConstraint(
            model_name="relacionsugerida",
            constraint=models.UniqueConstraint(
                fields=(
                    "parrafo",
                    "origen_texto",
                    "relation_type",
                    "destino_texto",
                    "fuente",
                ),
                name="unique_relacion_sugerida",
            ),
        ),
        migrations.AddConstraint(
            model_name="temporalidadsugerida",
            constraint=models.UniqueConstraint(
                fields=("parrafo", "fuente", "orientacion", "marcador"),
                name="unique_temporalidad_sugerida",
            ),
        ),
    ]
