# Generated by Django 4.2.4 on 2026-06-22 11:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EventLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_id", models.IntegerField(db_index=True, unique=True)),
                ("email", models.TextField(db_index=True)),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("name", models.TextField(db_index=True)),
                ("application", models.TextField(db_index=True)),
                ("orig_id", models.TextField(blank=True, db_column="origId")),
            ],
            options={
                "db_table": "logs_eventlog",
            },
        ),
        migrations.CreateModel(
            name="ProjectPlatformLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("research_project_uuid", models.UUIDField(db_index=True)),
                ("platform_slug", models.CharField(db_index=True, max_length=32)),
                ("is_primary", models.BooleanField(default=True)),
                ("activated_by_username", models.CharField(blank=True, max_length=150)),
                (
                    "activated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="projectplatformlink",
            constraint=models.UniqueConstraint(
                fields=("research_project_uuid", "platform_slug"),
                name="logs_unique_project_platform",
            ),
        ),
        migrations.AddIndex(
            model_name="eventlog",
            index=models.Index(
                fields=["application", "timestamp"],
                name="logs_eventl_applica_7f2301_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="eventlog",
            index=models.Index(
                fields=["name", "timestamp"], name="logs_eventl_name_e7b7f5_idx"
            ),
        ),
    ]
